language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run buildGithub
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $
  # keep-history: true
  on:
    branch: master